version: '3.8'

services:
  redis:
    image: "redis:alpine"
    restart: always
    environment:
      - REDIS_URL=redis://localhost:6379
    volumes:
      - redis_data:/data
    networks:
      - app-net
    ports:
      - "6379:6379"

  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: cheeseai
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - app-net

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - app-net

  app:
    build: .
    restart: always
    env_file: .env
    volumes:
      - .:/app
    depends_on:
      - redis
      - postgres
    networks:
      - app-net

networks:
  app-net:
    driver: bridge

volumes:
  redis_data:
  pg_data:
